name: Feature request
description: Propose an enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What should be added/changed?
    validations:
      required: true
