name: Release & Deploy

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for semantic-release to analyze commit history

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Create .env file for Next.js
        run: |
          echo "TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}" >> .env.local

      - name: Build Next.js App
        env:
          API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: npm run build

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }} # Use Personal Access Token (PAT) if needed
          API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: npx semantic-release

  deploy:
    needs: release # Runs after the release job is completed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull Vercel Environment Info
        run: vercel pull --yes --environment=production --token ${{ secrets.VERCEL_TOKEN }}

      - name: Create .env file for Deployment
        run: |
          echo "TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}" >> .env.local

      - name: Build Next.js App for Vercel
        run: vercel build --prod --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --prod --token ${{ secrets.VERCEL_TOKEN }}
