name: Require Linked Issue

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]

jobs:
  check:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.pull_request.body || "";
            const hasLink = /(close[sd]?|fix(e[sd])?|resolve[sd]?)\s+#\d+/i.test(body);
            if (!hasLink) {
              core.setFailed('PR must link an issue using e.g. "Closes #123".');
            }
